# Generated by Django 4.2.1 on 2023-05-29 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Blog", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="BlogContent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("user_mail", models.CharField(max_length=50)),
                ("blog_title", models.CharField(max_length=150)),
                (
                    "blog_image",
                    models.ImageField(upload_to="", verbose_name="BlogImage"),
                ),
                ("blog_content", models.TextField()),
            ],
        ),
    ]
