# Generated by Django 4.2.1 on 2023-05-31 06:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Blog", "0002_blogcontent"),
    ]

    operations = [
        migrations.AddField(
            model_name="blogcontent",
            name="blog_date",
            field=models.DateField(default=datetime.date.today),
        ),
    ]
